# Generated by Django 5.2.11 on 2026-02-16 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(help_text='예: CASE-2026-001', max_length=30, unique=True, verbose_name='케이스 ID')),
                ('name', models.CharField(help_text='예: 쿠팡 개인정보 유출', max_length=200, verbose_name='사건명')),
                ('description', models.TextField(blank=True, default='', verbose_name='사건 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사건 그룹',
                'verbose_name_plural': '사건 그룹',
                'db_table': 'case_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suitability', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_index=True, max_length=10, verbose_name='소송금융 적합도')),
                ('suitability_reason', models.TextField(verbose_name='판단 근거')),
                ('case_category', models.CharField(db_index=True, max_length=100, verbose_name='사건 분야')),
                ('defendant', models.CharField(blank=True, default='', max_length=200, verbose_name='상대방')),
                ('damage_amount', models.CharField(blank=True, default='', max_length=200, verbose_name='피해 규모(금액)')),
                ('victim_count', models.CharField(blank=True, default='', max_length=200, verbose_name='피해자 수')),
                ('stage', models.CharField(blank=True, choices=[('피해 발생', '피해 발생'), ('관련 절차 진행', '관련 절차 진행'), ('소송중', '소송중'), ('판결 선고', '판결 선고'), ('종결', '종결')], db_index=True, default='', max_length=50, verbose_name='진행 단계')),
                ('stage_detail', models.CharField(blank=True, default='', max_length=200, verbose_name='진행 단계 상세')),
                ('summary', models.TextField(verbose_name='요약')),
                ('llm_model', models.CharField(default='gpt-4o', max_length=50, verbose_name='사용 모델')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='프롬프트 토큰')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='응답 토큰')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='분석 시각')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='articles.article', verbose_name='기사')),
                ('case_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='analyses.casegroup', verbose_name='사건 그룹')),
            ],
            options={
                'verbose_name': 'AI 분석 결과',
                'verbose_name_plural': 'AI 분석 결과',
                'db_table': 'analyses',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['-analyzed_at'], name='analyses_analyze_1d686a_idx'), models.Index(fields=['suitability'], name='analyses_suitabi_ebf137_idx'), models.Index(fields=['case_category'], name='analyses_case_ca_b3d01c_idx')],
            },
        ),
    ]
