# Generated by Django 5.2.11 on 2026-02-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='is_relevant',
            field=models.BooleanField(db_index=True, default=True, help_text='법적 분쟁/소송과 관련 없는 기사는 False', verbose_name='법적 분쟁 관련'),
        ),
    ]
