# Generated by Django 5.2.11 on 2026-02-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_analysis_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='accepted',
            field=models.BooleanField(db_index=True, default=False, help_text='수임 대상으로 채택 여부 — 심사 완료 이후에만 True 가능', verbose_name='통과 여부'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='client_suitability',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='로앤굿이 직접 판단한 소송 적합도 (AI 결과와 다를 수 있음)', max_length=10, null=True, verbose_name='로앤굿 심사 결과'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='review_completed',
            field=models.BooleanField(db_index=True, default=False, help_text='로앤굿이 해당 사건을 검토 완료한 경우 True', verbose_name='심사 완료'),
        ),
    ]
