# Generated by Django 5.2.11 on 2026-02-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0002_analysis_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='damage_amount_num',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='파싱된 숫자 (원 단위). 미상이면 null.', null=True, verbose_name='피해 규모(원)'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='victim_count_num',
            field=models.IntegerField(blank=True, db_index=True, help_text='파싱된 숫자. 미상이면 null.', null=True, verbose_name='피해자 수(숫자)'),
        ),
    ]
