# Generated by Django 5.2.11 on 2026-02-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_add_review_fields'),
        ('analyses', '0004_backfill_numeric_fields'),
    ]

    operations = [
    ]
