# Generated by Django 5.2.11 on 2026-03-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0007_backfill_casegroup_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casegroup',
            name='case_id',
            field=models.CharField(help_text='예: 2026-02-001', max_length=30, unique=True, verbose_name='케이스 ID'),
        ),
    ]
