# Generated by Django 5.2.11 on 2026-03-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0008_alter_casegroup_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='llm_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=50, verbose_name='사용 모델'),
        ),
        migrations.AlterField(
            model_name='casegroup',
            name='name',
            field=models.CharField(db_index=True, help_text='예: 쿠팡 개인정보 유출', max_length=200, verbose_name='사건명'),
        ),
    ]
