# Generated by Django 5.2.11 on 2026-02-16 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='기사 URL')),
                ('author', models.CharField(blank=True, default='', max_length=100, verbose_name='기자')),
                ('published_at', models.DateTimeField(verbose_name='게재일')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일')),
                ('status', models.CharField(choices=[('pending', '분석 대기'), ('analyzing', '분석 중'), ('analyzed', '분석 완료'), ('failed', '분석 실패')], db_index=True, default='pending', max_length=20, verbose_name='분석 상태')),
                ('retry_count', models.IntegerField(default=0, verbose_name='재시도 횟수')),
            ],
            options={
                'verbose_name': '뉴스 기사',
                'verbose_name_plural': '뉴스 기사',
                'db_table': 'articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True, verbose_name='키워드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '수집 키워드',
                'verbose_name_plural': '수집 키워드',
                'db_table': 'keywords',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='MediaSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='언론사명')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='홈페이지')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '언론사',
                'verbose_name_plural': '언론사',
                'db_table': 'media_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.keyword')),
            ],
            options={
                'verbose_name': '기사-키워드',
                'verbose_name_plural': '기사-키워드',
                'db_table': 'article_keywords',
                'unique_together': {('article', 'keyword')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(related_name='articles', through='articles.ArticleKeyword', to='articles.keyword', verbose_name='키워드'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.mediasource', verbose_name='언론사'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='articles_publish_aa799f_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='articles_status_a4f178_idx'),
        ),
    ]
